# Clean Data for Presidential Party Wins by State
This notebook takes in a CSV of data from a Wikipedia table and cleans it for export to CSV and use in Tableau

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

### Import CSV File
I used the site https://wikitable2csv.ggor.de/ to convert the table of presidential wins by state from https://en.wikipedia.org/wiki/List_of_United_States_presidential_election_results_by_state into a CSV file

In [2]:
input_file = 'raw_data/pres_wins_by_state.csv'
df = pd.read_csv(input_file)
df.sample(5)

,State,1789,1792,1796,1800,Unnamed: 5,1804,1808,1812,1816,1820,1824 †,1828,1832,1836,1840,Unnamed: 16,1844,1848,1852,1856,1860,1864,1868,1872,1876 ‡,1880,Unnamed: 27,1884,1888 ‡,1892,1896,1900,1904,1908,1912,1916,1920,Unnamed: 38,1924,1928,1932,1936,1940,1944,1948,1952,1956,1960,Unnamed: 49,1964,1968,1972,1976,1980,1984,1988,1992,1996,2000 ‡,Unnamed: 60,2004,2008,2012,2016 ‡,2020,State.1
30,New Hampshire,GW,GW,F,F,NaN,DR,F,F,DR,DR,Adams,NR,D,D,D,NaN,D,D,D,R,R,R,R,R,R,R,NaN,R,R,R,R,R,R,R,D,D,R,NaN,R,R,R,D,D,D,R,R,R,R,NaN,D,R,R,R,R,R,R,D,D,R,NaN,D,D,D,D,D,New Hampshire
31,New Jersey,GW,GW,F,F,NaN,DR,DR,F,DR,DR,Jackson,NR,D,W,W,NaN,W,W,D,D,R,D,D,R,D,D,NaN,D,D,D,R,R,R,R,D,R,R,NaN,R,R,D,D,D,D,R,R,R,D,NaN,D,R,R,R,R,R,R,D,D,D,NaN,D,D,D,D,D,New Jersey
7,Delaware,GW,GW,F,F,NaN,F,F,F,F,DR,Crawford,NR,NR,W,W,NaN,W,W,D,D,SD,D,D,R,D,D,NaN,D,D,D,R,R,R,R,D,R,R,NaN,R,R,R,D,D,D,R,R,R,D,NaN,D,R,R,D,R,R,R,D,D,D,NaN,D,D,D,D,D,Delaware
29,Nevada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R,R,R,R,D,NaN,R,R,PO,D,D,R,D,D,D,R,NaN,R,R,D,D,D,D,D,R,R,D,NaN,D,R,R,R,R,R,R,D,D,R,NaN,R,D,D,D,D,Nevada
32,New Mexico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,D,R,NaN,R,R,D,D,D,D,D,R,R,D,NaN,D,R,R,R,R,R,R,D,D,D,NaN,R,D,D,D,D,New Mexico

### Remove Unnecessary Columns
Keep only column names that are 'State' or start with a number

In [3]:
state_col = 'State'
year_cols_trimmed = df.columns.str.slice(0,4)
year_cols_mask = year_cols_trimmed.str.isnumeric()
keep_cols = [state_col] + df.columns[year_cols_mask].tolist()

df = df[keep_cols]
df.columns = [state_col] + year_cols_trimmed[year_cols_mask].tolist()
df.sample(5)

,State,1789,1792,1796,1800,1804,1808,1812,1816,1820,1824,1828,1832,1836,1840,1844,1848,1852,1856,1860,1864,1868,1872,1876,1880,1884,1888,1892,1896,1900,1904,1908,1912,1916,1920,1924,1928,1932,1936,1940,1944,1948,1952,1956,1960,1964,1968,1972,1976,1980,1984,1988,1992,1996,2000,2004,2008,2012,2016,2020
16,Kansas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R,R,R,R,R,R,R,PO,D,R,R,R,D,D,R,R,R,D,D,R,R,R,R,R,R,D,R,R,R,R,R,R,R,R,R,R,R,R,R,R
18,Louisiana,NaN,NaN,NaN,NaN,NaN,NaN,DR,DR,DR,Jackson,D,D,D,W,D,W,D,D,SD,R,D,R,R,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,SR,D,R,D,R,AI,R,D,R,R,R,D,D,R,R,R,R,R,R
31,New Jersey,GW,GW,F,F,DR,DR,F,DR,DR,Jackson,NR,D,W,W,W,W,D,D,R,D,D,R,D,D,D,D,D,R,R,R,R,D,R,R,R,R,D,D,D,D,R,R,R,D,D,R,R,R,R,R,R,D,D,D,D,D,D,D,D
10,Georgia,GW,GW,DR,DR,DR,DR,DR,DR,DR,Crawford,D,D,W,W,D,W,D,D,SD,NaN,D,LR,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,R,AI,R,D,D,R,R,D,R,R,R,R,R,R,D
41,South Carolina,GW,GW,DR,DR,DR,DR,DR,DR,DR,Jackson,D,N,W,D,D,D,D,D,SD,NaN,R,R,R,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,SR,D,D,D,R,R,R,D,R,R,R,R,R,R,R,R,R,R,R

### Remove Unnecessary Rows
There are some extra rows containing repeats of the column headers

In [4]:
df = df[df['State'] != 'State'].reset_index(drop=True)
df.tail()

,State,1789,1792,1796,1800,1804,1808,1812,1816,1820,1824,1828,1832,1836,1840,1844,1848,1852,1856,1860,1864,1868,1872,1876,1880,1884,1888,1892,1896,1900,1904,1908,1912,1916,1920,1924,1928,1932,1936,1940,1944,1948,1952,1956,1960,1964,1968,1972,1976,1980,1984,1988,1992,1996,2000,2004,2008,2012,2016,2020
46,Virginia,GW,GW,DR,DR,DR,DR,DR,DR,DR,Crawford,D,D,D,D,D,D,D,D,CU,NaN,NaN,R,D,D,D,D,D,D,D,D,D,D,D,D,D,R,D,D,D,D,D,R,R,R,D,R,R,R,R,R,R,R,R,R,R,D,D,D,D
47,Washington,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R,D,R,R,R,BM,D,R,R,R,D,D,D,D,D,R,R,R,D,D,R,R,R,R,D,D,D,D,D,D,D,D,D
48,West Virginia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R,R,R,D,D,D,D,D,R,R,R,R,D,R,R,R,R,D,D,D,D,D,D,R,D,D,D,R,D,D,R,D,D,D,R,R,R,R,R,R
49,Wisconsin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,D,R,R,R,R,R,R,R,R,R,D,R,R,R,R,D,R,R,PR,R,D,D,D,R,D,R,R,R,D,R,R,D,R,R,D,D,D,D,D,D,D,R,D
50,Wyoming,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R,D,R,R,R,D,D,R,R,R,D,D,D,R,D,R,R,R,D,R,R,R,R,R,R,R,R,R,R,R,R,R,R

### Substitute Similar Parties
Since the Southern Democratic, Northern Democratic, and States' Rights Democratic Parties were all short-lived parties that broke off from the Democratic Party I'm combining them into a single party for simplicity of analysis.

In [5]:
value_subs = {'SD':'D', 'ND':'D', 'SR':'D'}
df.replace(value_subs, inplace=True)
df.sample(5)

,State,1789,1792,1796,1800,1804,1808,1812,1816,1820,1824,1828,1832,1836,1840,1844,1848,1852,1856,1860,1864,1868,1872,1876,1880,1884,1888,1892,1896,1900,1904,1908,1912,1916,1920,1924,1928,1932,1936,1940,1944,1948,1952,1956,1960,1964,1968,1972,1976,1980,1984,1988,1992,1996,2000,2004,2008,2012,2016,2020
28,Nevada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R,R,R,R,D,R,R,PO,D,D,R,D,D,D,R,R,R,D,D,D,D,D,R,R,D,D,R,R,R,R,R,R,D,D,R,R,D,D,D,D
2,Arizona,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,D,R,R,R,D,D,D,D,D,R,R,R,R,R,R,R,R,R,R,R,D,R,R,R,R,R,D
23,Minnesota,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R,R,R,R,R,R,R,R,R,R,R,R,R,BM,R,R,R,R,D,D,D,D,D,R,R,D,D,D,R,D,D,D,D,D,D,D,D,D,D,D,D
32,New York,NaN,GW,F,DR,DR,DR,F,DR,DR,Adams,D,D,D,W,D,W,D,R,R,R,D,R,D,R,D,R,D,R,R,R,R,D,R,R,R,R,D,D,D,D,R,R,R,D,D,D,R,D,R,R,D,D,D,D,D,D,D,D,D
44,Utah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,R,R,R,R,D,R,R,R,D,D,D,D,D,R,R,R,D,R,R,R,R,R,R,R,R,R,R,R,R,R,R

### Keep Only Democratic and Republican Wins
I'm only concerned about these two parties so I'm turning any other non-null value into 'O' for other

In [6]:
other_party = (~df.isin(['D', 'R']) & df.notna())
other_party['State'] = False
df[other_party] = 'O'
df.dropna(axis=1, how='all', inplace=True)
df.head()

,State,1789,1792,1796,1800,1804,1808,1812,1816,1820,1824,1828,1832,1836,1840,1844,1848,1852,1856,1860,1864,1868,1872,1876,1880,1884,1888,1892,1896,1900,1904,1908,1912,1916,1920,1924,1928,1932,1936,1940,1944,1948,1952,1956,1960,1964,1968,1972,1976,1980,1984,1988,1992,1996,2000,2004,2008,2012,2016,2020
0,Alabama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,O,O,D,D,D,D,D,D,D,D,D,NaN,R,R,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,O,R,O,R,D,R,R,R,R,R,R,R,R,R,R,R
1,Alaska,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R,D,R,R,R,R,R,R,R,R,R,R,R,R,R,R
2,Arizona,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,D,R,R,R,D,D,D,D,D,R,R,R,R,R,R,R,R,R,R,R,D,R,R,R,R,R,D
3,Arkansas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,D,D,D,D,D,D,NaN,R,R,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,O,R,D,R,R,R,D,D,R,R,R,R,R,R
4,California,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,D,R,R,R,R,R,D,R,R,D,R,R,R,R,O,D,R,R,R,D,D,D,D,D,R,R,R,D,R,R,R,R,R,R,D,D,D,D,D,D,D,D

### Unpivot Year Columns Into Rows
Setting up the data the way Tableau likes it

In [7]:
state_col = [df.columns[0]]
year_cols = df.columns[1:]

df = pd.melt(df, id_vars=state_col, value_vars=year_cols, var_name='Year', value_name='Party')
df = df.sort_values(['State', 'Year']).reset_index(drop=True)
df.head()

     State  Year Party
0  Alabama  1789   NaN
1  Alabama  1792   NaN
2  Alabama  1796   NaN
3  Alabama  1800   NaN
4  Alabama  1804   NaN

### Add a Column Tracking Party Switches
1 if the state's winning party switched from D to R or R to D since the last election, 0 if it stayed the same

In [8]:
prev_winners = df.groupby('State')['Party'].shift(1)
winner_pairs = df['Party'] + prev_winners
df['Switch'] = winner_pairs.isin(['DR', 'RD']).astype(int)

### Export DataFrame to CSV

In [9]:
output_file = '../data/pres_wins_by_state.csv'
df.to_csv(output_file, index=False)